InternationalWaterWebApp/InternationalWaterWebApp/Controllers/ProducerController.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Office2010.Excel;
using InternationalWaterWebApp.Library.Common;
using InternationalWaterWebApp.Library.ViewModel;
using InternationalWaterWebApp.Models;
using InternationalWaterWebApp.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace InternationalWaterWebApp.Controllers
{
    [AuthorizationCS((int)UserTypeEnum.Producer)]
    public class ProducerController : BaseController
    {
        private CommonMethods commonMethods;
        private EncryptDecryptData encryptDecryptData;
        public ProducerController()
        {
            commonMethods = new CommonMethods();
            encryptDecryptData = new EncryptDecryptData();
        }
        public IActionResult Landing(string DropdownFrom, string DropdownTo)
        {
            IMasterRepository _masterRepository = new MasterRepository();
            try
            {
                string yearfrom = string.Empty, yearto = string.Empty;

                var Producer_Id = commonMethods.GetProducerByUserID(LoginUserId);
                DataSet currentyeardata = null;
                string currentyear = $"select * from \"FSRCalc\".water_frs_get_years_by_producer_id(datarefcursor =>'data',_producer_id => {Producer_Id});";
                currentyeardata = _masterRepository.GetAndSelectTableItems(currentyear);
                DataTable currentyear_data_DT = currentyeardata.Tables.Count > 0 ? currentyeardata.Tables[0] : null;
                if (currentyear_data_DT != null && currentyear_data_DT.Rows.Count > 0)
                {
                    yearfrom = currentyear_data_DT.Rows[0][0].ToString();
                    int lastIndex = currentyear_data_DT.Rows.Count - 1;
                    yearto = currentyear_data_DT.Rows[lastIndex][0].ToString();
                }

                string valuefrom = DropdownFrom ?? yearfrom;
                string valueto = DropdownTo ?? yearto;

                List<SelectListItem> li = new List<SelectListItem>();
                foreach (DataRow row in currentyeardata.Tables[0].Rows)
                {
                    li.Add(new SelectListItem() { Text = row["year"].ToString(), Value = row["year"].ToString() });
                }
                ViewBag.Dropdownfrom = new SelectList(li, "Value", "Text", valuefrom);
                ViewBag.Dropdownto = new SelectList(li, "Value", "Text", valueto);

                object[] agrParams = { "_ActionType", "_user_id" };
                object[] agrValues = { "GetAdvisorByProducer", LoginUserId };

                DataSet dsAdvisorData = _masterRepository.GetAndSelectTableItems($"SELECT * from \"Users\".water_advisors_ref (datarefcursor => 'data',{agrParams[0]} => '{agrValues[0]}',{agrParams[1]}=>{agrValues[1]});");
                ViewBag.AdvisorInfo = dsAdvisorData;
                if (dsAdvisorData != null && dsAdvisorData.Tables[0].Rows.Count > 0)
                {
                    var advisoremail = Convert.ToString(dsAdvisorData.Tables[0].Rows[0]["email"]);
                    HttpContext.Session.SetString("AdvisorEmail", advisoremail);
                }

                object[] userParams = { "_ActionType", "_producer_id" };
                object[] userFarmValues = { "GetFarmByProducerId", Producer_Id };
                object[] userFieldValues = { "GetFieldByProducerId", Producer_Id };

                //string QueryFarm = $"SELECT * from  \"FSRCalc\".water_producer_ref (datarefcursor => 'data',{userParams[0]} => '{userFarmValues[0]}',{userParams[1]} => {userFarmValues[1]});";
                //DataSet DsFarmData = _masterRepository.GetAndSelectTableItems(QueryFarm, userParams, userFarmValues);
                //ViewBag.Farm = DsFarmData;

                int firstValue = Convert.ToInt32(valuefrom == string.Empty ? 0 : valuefrom);
                int secondValue = Convert.ToInt32(valueto == string.Empty ? 0 : valueto);

                string QueryFarm = $"SELECT * from \"FSRCalc\".frs_new_get_farms_details1(_producer_id => {Producer_Id});";
                DataSet DsFarmData = _masterRepository.GetAndSelectTableItemsWithoutCursor(QueryFarm);
                ViewBag.Farm = DsFarmData;

                string QueryFarm2 = string.Empty;
                DataSet DsFarmData2 = new DataSet();
                if (firstValue != 0 && secondValue != 0)
                {
                    QueryFarm2 = $"SELECT * from \"FSRCalc\".frs_new_get_farms_details2(_producer_id => {Producer_Id} , yearfrom => {firstValue} , yearto => {secondValue},_actiontype=>'GetWithYear');";
                    DsFarmData2 = _masterRepository.GetAndSelectTableItemsWithoutCursor(QueryFarm2);
                }
                else
                {
                    QueryFarm2 = $"SELECT * from \"FSRCalc\".frs_new_get_farms_details2(_producer_id => {Producer_Id} , yearfrom => {firstValue} , yearto => {secondValue},_actiontype=>'GetWithoutYear');";
                    DsFarmData2 = _masterRepository.GetAndSelectTableItemsWithoutCursor(QueryFarm2);

                }
                ViewBag.Farm2 = DsFarmData2;
                //string QueryFarm2 = $"SELECT * from \"FSRCalc\".frs_new_get_farms_details2(_producer_id => {Producer_Id} , yearfrom => {firstValue} , yearto => {secondValue},_actiontype=>'GetWithYear');";
                //DataSet DsFarmData2 = _masterRepository.GetAndSelectTableItemsWithoutCursor(QueryFarm2);
                //ViewBag.Farm2 = DsFarmData2;

                string QueryFarm3 = $"SELECT * from \"FSRCalc\".frs_new_get_farms_details3(_producer_id => {Producer_Id} , yearfrom => {firstValue} , yearto => {secondValue},_actiontype=>'GetWithYear');";
                DataSet DsFarmData3 = _masterRepository.GetAndSelectTableItemsWithoutCursor(QueryFarm3);
                ViewBag.Farm3 = DsFarmData3;


                DataTable fsr_data = DsFarmData.Tables[0];
                decimal FarmaerSRatingBox = 0;
                decimal FarmaerareaBox = 0;
                decimal totalarea;
                if (DsFarmData != null && DsFarmData.Tables.Count > 0 && DsFarmData.Tables[0] != null)
                {
                    for (int i = 0; i < DsFarmData3.Tables[0]?.Rows.Count; i++)
                    {

                        decimal FarmerSRatingBox = DsFarmData3.Tables[0]?.Rows[i]["total_fsr"].ToString() != null ? Convert.ToDecimal(DsFarmData3.Tables[0]?.Rows[i]["total_fsr"].ToString()) : 0.0M;

                        decimal TotalArea = DsFarmData3.Tables[0]?.Rows[i]["total_area"].ToString() != null ? Convert.ToDecimal(DsFarmData3.Tables[0]?.Rows[i]["total_area"].ToString()) : 0.0M;

                        decimal result = FarmerSRatingBox * TotalArea;

                        FarmaerSRatingBox += result;
                        if (decimal.TryParse(DsFarmData3.Tables[0]?.Rows[i]["total_area"].ToString(), out totalarea))
                        {
                            FarmaerareaBox += totalarea;
                        }
                    }
                }

                ViewBag.FSRBox = FarmaerareaBox != 0.00M ? FarmaerSRatingBox / FarmaerareaBox : 0.00M;

                string QueryField = $"SELECT * from  \"FSRCalc\".water_producer_ref (datarefcursor => 'data',{userParams[0]} => '{userFieldValues[0]}',{userParams[1]} => {userFieldValues[1]});";
                DataSet DsFieldData = _masterRepository.GetAndSelectTableItems(QueryField);
                ViewBag.Field = DsFieldData;
                return View();
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Login", "WebApp");
            }
        }

        public IActionResult MyFields(string DropdownFrom, string DropdownTo)
        {
            try
            {
                var Producer_Id = commonMethods.GetProducerByUserID(LoginUserId);
                IMasterRepository _masterRepository = new MasterRepository();

                DataSet currentyeardata = null;
                string currentyear = $"select * from \"FSRCalc\".water_frs_get_years_by_producer_id(datarefcursor =>'data',_producer_id => {Producer_Id});";
                currentyeardata = _masterRepository.GetAndSelectTableItems(currentyear);

                DataTable currentyeardataDT = currentyeardata?.Tables[0];
                string yearfrom = currentyeardataDT?.Rows.Count > 0 ? currentyeardataDT.Rows[0][0]?.ToString() : string.Empty;
                string yearto = currentyeardataDT?.Rows.Count > 0 ? currentyeardataDT.Rows[^1][0]?.ToString() : string.Empty;

                string valuefrom = DropdownFrom ?? yearfrom ?? string.Empty;
                string valueto = DropdownTo ?? yearto ?? string.Empty;

                int firstValue = Convert.ToInt32(valuefrom == string.Empty ? 0 : valuefrom);
                int secondValue = Convert.ToInt32(valueto == string.Empty ? 0 : valueto);

                List<SelectListItem> li = currentyeardataDT?.AsEnumerable()
                .Select(row => new SelectListItem
                {
                    Text = row["year"].ToString(),
                    Value = row["year"].ToString()
                }).ToList() ?? new List<SelectListItem>();

                //ViewBag.Dropdownfrom = new SelectList(li, "Value", "Text", valuefrom);
                //ViewBag.Dropdownto = new SelectList(li, "Value", "Text", valueto);

                object[] userParams = { "_ActionType", "_producer_id" };
                object[] userValues = { "GetFieldByProducerId", Producer_Id };
                //  string query = $"SELECT * from  \"FSRCalc\".water_producer_Fieldref (datarefcursor => 'data',{userParams[0]} => '{userValues[0]}',{userParams[1]} => {userValues[1]});";
                string query = $"SELECT * from  \"FSRCalc\".water_producer_Fieldref (datarefcursor => 'data',_producer_id => {Producer_Id} , yearfrom => {firstValue} , yearto => {secondValue});";

InternationalWaterWebApp/InternationalWaterWebApp/Views/Producer/Landing.cshtml
@using System.Data;
@using InternationalWaterWebApp.Library.Common

@{
    ViewData["Title"] = "Landing Page";
    EncryptDecryptData enc = new EncryptDecryptData();
}

@if (!string.IsNullOrWhiteSpace(Convert.ToString(TempData["Success"])))
{
    <div class="alert alert-success mt-3" role="alert">
        @TempData["Success"]
    </div>
}
@if (!string.IsNullOrWhiteSpace(Convert.ToString(TempData["Error"])))
{
    <div class="alert alert-danger mt-3" role="alert">
        @TempData["Error"]
    </div>
}

<section class="GreyBG rounded-3 py-3">
    <div class="container-fluid">
        <div class="row g-3">
            <div class="col-lg-8 col-12">
                <div class="bg-white WelWayFindr br-10 p-3 mb-3">
                    <div class="Heading">
                        <h2>Welcome to WayFindr</h2>
                    </div>
                    <div class="row g-3">
                        <div class="col-lg-auto">
                            <div class="br-10 Ratig text-center">
                                @if (ViewBag.FSRBox != 0)
                                {
                                    var ratingValue = @Math.Round(Convert.ToDouble(ViewBag.FSRBox), 2);
                                    <span>@ratingValue.ToString("0.00")</span>
                                }
                                else
                                {
                                    <span>N/A</span>
                                }
                                <p>Farmer Stewardship Rating</p>
                            </div>
                        </div>
                        <div class="col">
                            <p class="align-justify">
                                @* The stewardship rating reflects the quality of your operation for all of your farms and the fields comprising each farm. The value ranges from 0 to 10, is adjusted for the size of each field and farm, and is based on specific environmental outcomes and stewardship indices that reflect your actual farming methods.*@
                                Thank you for placing your trust in the International Water Institute’s Steward Program (SP). The SP focuses on realizing continuous improvements in the farm operation by exploring and implementing change that reflects the values of the Producer, rather than “selling” conservation or a specific farming method. Wayfinder provides you with the means to explore your ability to increase profitability, while understanding the implications of your operation on land stewardship and environmental outcomes. <br />
                                Not only do receive direct value through the SP, you’re empowered to explore and test the viability of secondary markets (e.g., premium commodity pricing, preferred lending rates) using the Patent Pending Stewardship Rating.
                            </p>
                            @*<p class="TxtDecor">
                            • Aliquam vel eros facilisis, cursus ante ac, interdum eros.
                            <br>
                            • Ut tristique et purus eget varius.
                            <br>
                            • Fusce iaculis dignissim justo, viverra ultricies risus rutrum sed.
                            </p>
                            <br />*@
                            <br />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-12">
                <div class="br-10 bg-white p-3 mb-3">
                    <div class="MessAdvisr">
                        <div class="Heading">
                            <h4 class="text-center">Message My Advisor</h4>
                        </div>
                        @if (ViewBag.AdvisorInfo?.Tables[0]?.Rows?.Count > 0)
                        {
                            @foreach (System.Data.DataRow Row in ViewBag.AdvisorInfo.Tables[0].Rows)
                            {
                                @* <div>Message My Advisor</div>*@
                                <div><b>Advisor Name: </b> @Convert.ToString(Row["first_name"])  @Convert.ToString(Row["last_name"])</div>
                                <br />
                                <div>
                                    <b>Phone: </b>
                                    @{

                                        var displayPhone = !string.IsNullOrEmpty(Convert.ToString(Row["phone_mobile"])) ? string.Format("({0:###) ###-####}", long.Parse(Convert.ToString(Row["phone_mobile"]))) : "N/A";
                                    }
                                    @displayPhone
                                </div>
                                <br />
                                <div><b>Email: </b> @Convert.ToString(Row["email"])</div>
                                <br />
                            }
                        }
                        else
                        {
                            <div>No Advisor Assigned</div>
                        }
                        <div class="d-grid bg-green advsrBTN">
                            <a href="javascript:;" class="btn" id="btnSendMessageToAdvisor"><i class="fa fa-plus"></i> Send Message </a>
                        </div>
                    </div>
                </div>
                @* <div class="br-10 bg-white p-3">
                <div class="MessAdvisr">
                <div class="Heading">
                <h4 class="text-center">Key Resources</h4>
                </div>
                <div class="d-grid mb-2 kyResors mb-4">
                <a href="#">Your Options</a>
                </div>
                <div class="d-grid mb-2 kyResors mb-4">
                <a href="#">Field Setting</a>
                </div>
                <div class="d-grid mb-2 kyResors mb-4">
                <a href="#">Management Zones</a>
                </div>
                </div>
                </div>*@
            </div>
        </div>
        <div class="col-lg-12 col-12">
            <div class="bg-white WelWayFindr br-10 p-3 mb-3">
                <div class="Heading">
                    <h2>My Farms</h2>
                </div>
                <div class="innerPgeHeading  d-flex justify-content-between row">
                    <p class="col-md-6 col-sm-12">The stewardship rating and environmental outcomes for each farm reflect the results for each field, adjusted for field size. </p>

                    @*<h3>@ViewBag.FieldName</h3>*@
                    @using (Html.BeginForm("Landing", "Producer", FormMethod.Post, new
                    {
                        @class = "col-md-5 mb-2",@* style = "margin-top: -13px;"*@ }))
                    {
                        @Html.Hidden("id", ViewBag.FieldId, new { })
                        @Html.Hidden("name", ViewBag.FieldName, new { })
                        <div class="inline-dropdowns d-flex justify-content-space-between align-items-center">
                            <span class="Myfarmoperations">Operations Year:</span>
                            @Html.DropDownList("DropdownFrom", (IEnumerable<SelectListItem>)ViewBag.Dropdownfrom, new { @class = "form-select w-30", onchange = "this.form.submit();", AutoPostBack = "true" })
                            <span>to</span>
                            @Html.DropDownList("DropdownTo", (IEnumerable<SelectListItem>)ViewBag.Dropdownto, new { @class = "form-select w-30", onchange = "this.form.submit();", AutoPostBack = "true" })
                        </div>
                    }
                </div>
                <table class="table table-striped table-responsive table-borderless" id="ProducerLandingFarm">
                    <thead>
                        <tr>
                            <th>Farms</th>
                            <th># of Fields</th>
                            <th>Acres</th>
                            <th>% of Enterprise</th>
                            <th>Farm Stewardship Rating</th>
                            <th>Stewardship Letter Grade</th>
                            <th>Avg Net Return </th>
                            <th>Avg Production Cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Farm?.Tables[0]?.Rows?.Count > 0 && ViewBag.Farm2?.Tables.Count > 0)
                        {
                            int rowCount = Math.Max(ViewBag.Farm?.Tables.Count > 0 ? ViewBag.Farm.Tables[0]?.Rows?.Count ?? 0 : 0, ViewBag.Farm2?.Tables.Count > 0 ? ViewBag.Farm2.Tables[0]?.Rows?.Count ?? 0 : 0);
                            @* int averagesCount = ViewBag.Averages?.Count ?? 0;
                        int gradesCount = ViewBag.Grades?.Count ?? 0;
                        int loopLength = Math.Min(rowCount, Math.Min(averagesCount, gradesCount));*@

                            if (rowCount > 0)
                            {
                                for (int i = 0; i < rowCount; i++)
                                {
                                    <tr>
                                        <td>
                                            <a asp-controller="Producer" asp-action="MyFarmDetails" asp-route-id="@enc.Encryptdata(Convert.ToString(ViewBag.Farm.Tables[0].Rows[i]["farm_id"]))" asp-route-name="@ViewBag.Farm.Tables[0].Rows[i]["farm_name"]">
                                                @Convert.ToString(ViewBag.Farm.Tables[0].Rows[i]["farm_name"])
                                            </a>
                                        </td>
                                        <td>

                                            @(ViewBag.Farm?.Tables[0]?.Rows[i]["field_count"] ?? "")

                                        </td>
                                        <td>
                                            @{
                                                var acresRaw = ViewBag.Farm?.Tables[0]?.Rows[i]["acres"];
                                                var formattedAcres = acresRaw != null
                                                ? string.Format("{0:#,##0.##}", Convert.ToDouble(acresRaw))
                                                : "";
                                            }
                                            @formattedAcres
                                        </td>
                                        @*<td>
                            @(ViewBag.Farm?.Tables[0]?.Rows[i]["enterprise"] != null ? ((decimal)ViewBag.Farm.Tables[0].Rows[i]["enterprise"]).ToString("0.00") : "") %
                            </td>*@
                                        <td>@(!Convert.IsDBNull(ViewBag.Farm?.Tables[0]?.Rows[i]["enterprise"]) ? (ViewBag.Farm.Tables[0].Rows[i]["enterprise"]) : "") </td>
                                        <td>
                                            @(Convert.IsDBNull(ViewBag.Farm3?.Tables[0]?.Rows[i]["total_fsr"]) || Convert.ToDouble(ViewBag.Farm3?.Tables[0]?.Rows[i]["total_fsr"]) == 0 ? "-" : Convert.ToDouble(ViewBag.Farm3?.Tables[0]?.Rows[i]["total_fsr"]).ToString())
                                        </td>

                                        <td>@(!Convert.IsDBNull(ViewBag.Farm3?.Tables[0]?.Rows[i]["avgoverall_rating"]) ? (ViewBag.Farm3.Tables[0].Rows[i]["avgoverall_rating"]) : "-") </td>
                                        @* <td>
                            @(i < averagesCount ? (ViewBag.Averages[i]?.Average != null && ViewBag.Averages[i]?.Average.ToString("0.00") != "0.00" ? ViewBag.Averages[i]?.Average.ToString("0.00") : "-") : "-"
                            )
                            </td>
                            <td>
                            @(i < gradesCount ? (ViewBag.Grades[i] != null && ViewBag.Grades[i] != "" ? ViewBag.Grades[i] : "-") : "-"
                            )
                            </td>*@
                                        <td>
                                            @*@(ViewBag.Farm2?.Tables[0]?.Rows[i]["net_return"] ?? "")*@
                                            @if (ViewBag.Farm2?.Tables[0]?.Rows != null && i >= 0 && i < ViewBag.Farm2.Tables[0].Rows.Count)
                                            {
                                                @ViewBag.Farm2.Tables[0].Rows[i]["net_return"]
                                                ;

                                            }
                                            else
                                            {
                                                <text>0</text>
                                            }
                                        </td>
                                        <td>
                                            @if (ViewBag.Farm2?.Tables[0]?.Rows != null && i >= 0 && i < ViewBag.Farm2.Tables[0].Rows.Count)
                                            {
                                                @ViewBag.Farm2.Tables[0].Rows[i]["production_cost"]
                                                ;
                                            }
                                            else
                                            {
                                                <text>0</text>
                                            }

                                            @*@(ViewBag.Farm2?.Tables[0]?.Rows[i]["production_cost"] ?? "")*@
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="8"> data not available.</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

InternationalWaterWebApp/InternationalWaterWebApp/Views/Producer/MyFarms.cshtml
@using System.Data;
@using InternationalWaterWebApp.Library.Common
@{
    ViewData["Title"] = "Landing Page";
    EncryptDecryptData enc = new EncryptDecryptData();
}

@if (!string.IsNullOrWhiteSpace(Convert.ToString(TempData["Success"])))
{
    <div class="alert alert-success mt-3" role="alert">
        @TempData["Success"]
    </div>
}
@if (!string.IsNullOrWhiteSpace(Convert.ToString(TempData["Error"])))
{
    <div class="alert alert-danger mt-3" role="alert">
        @TempData["Error"]
    </div>
}

<section class="GreyBG rounded-3 py-3">
    <div class="container-fluid">
        <div class="row g-3">
            <div class="col-lg-12 col-12">
                <div class="bg-white WelWayFindr br-10 p-3 mb-3">
                    <div class="Heading">
                        <h2>My Farms</h2>
                    </div>
                    <p>The stewardship rating and environmental outcomes for each farm reflect the results for each field, adjusted for field size. </p>
                    <div class="innerPgeHeading mb-4 justify-content-between">
                        <h3>@ViewBag.FieldName</h3>
                        @using (Html.BeginForm("MyFarms", "Producer", FormMethod.Post, new { @class = "w-40" }))
                        {
                            @Html.Hidden("id", ViewBag.FieldId, new { })
                            @Html.Hidden("name", ViewBag.FieldName, new { })
                           @* <div class="inline-dropdowns d-flex justify-content-space-between align-items-center">
                                <span class="Myfarmoperations">Operations Year:</span>
                                @Html.DropDownList("DropdownFrom", (IEnumerable <SelectListItem>)ViewBag.Dropdownfrom , new { @class = "form-select w-30", onchange = "this.form.submit();", AutoPostBack = "true" } )
                                <span>to</span>
                                @Html.DropDownList("DropdownTo", (IEnumerable <SelectListItem>)ViewBag.Dropdownto , new { @class = "form-select w-30", onchange = "this.form.submit();", AutoPostBack = "true" } )
                            </div>*@
                        }
                    </div>
                    <table class="table table-striped table-responsive table-borderless" id="ProducerLandingFarm">
                        <thead>
                            <tr>
                                <th>Farms</th>
                                <th># of Fields</th>
                                <th>Acres</th>
                                <th>% of Enterprise</th>
                                <th>Farm Stewardship Rating</th>
                                <th>Stewardship Letter Grade</th>
                                <th>Avg Net Return </th>
                                <th>Avg Production Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (ViewBag.Farm?.Tables[0]?.Rows?.Count > 0 && ViewBag.Farm2?.Tables.Count > 0)
                            {
                                int rowCount = Math.Max(ViewBag.Farm?.Tables.Count > 0 ? ViewBag.Farm.Tables[0]?.Rows?.Count ?? 0 : 0, ViewBag.Farm2?.Tables.Count > 0 ? ViewBag.Farm2.Tables[0]?.Rows?.Count ?? 0 : 0);

                                if (rowCount > 0)
                                {
                                    for (int i = 0; i < rowCount; i++)
                                    {
                                        <tr>
                                            @*<td> <a asp-area="" asp-controller="Producer" asp-action="MyFarmDetails" class="ms-3">@(ViewBag.Farm?.Tables[0]?.Rows[i]["farm_name"] ?? "")</a></td>*@
                                            @*<td><a asp-controller="Producer" asp-action="MyFarmDetails" asp-route-id="@enc.Encryptdata(Convert.ToString(47))" asp-route-name="@ViewBag.Farm.Tables[0].Rows[i]["farm_name"]">@Convert.ToString(ViewBag.Farm.Tables[0].Rows[i]["farm_name"])</a></td>*@
                                            <td>
                                                <a asp-controller="Producer" asp-action="MyFarmDetails" asp-route-id="@enc.Encryptdata(Convert.ToString(ViewBag.Farm.Tables[0].Rows[i]["farm_id"]))" asp-route-name="@ViewBag.Farm.Tables[0].Rows[i]["farm_name"]">
                                                    @Convert.ToString(ViewBag.Farm.Tables[0].Rows[i]["farm_name"])
                                                </a>
                                            </td>
                                            <td>
                                                @(
                                                    ViewBag.Farm?.Tables[0]?.Rows[i]["field_count"] ?? ""
                                                    )
                                            </td>
                                            <td>
                                                @{
                                                    var acresRaw = ViewBag.Farm?.Tables[0]?.Rows[i]["acres"];
                                                    var formattedAcres = acresRaw != null
                                                    ? string.Format("{0:#,##0.##}", Convert.ToDouble(acresRaw))
                                                    : "";
                                                }
                                                @formattedAcres
                                            </td>
                                            <td>
                                                @(
                                                    !Convert.IsDBNull(ViewBag.Farm?.Tables[0]?.Rows[i]["enterprise"]) ? (ViewBag.Farm.Tables[0].Rows[i]["enterprise"]) : ""
                                                    )
                                            </td>
                                            <td>@(!Convert.IsDBNull(ViewBag.Farm3?.Tables[0]?.Rows[i]["total_fsr"]) ? (ViewBag.Farm3.Tables[0].Rows[i]["total_fsr"]) : "-") </td>
                                            <td>@(!Convert.IsDBNull(ViewBag.Farm3?.Tables[0]?.Rows[i]["avgoverall_rating"]) ? (ViewBag.Farm3.Tables[0].Rows[i]["avgoverall_rating"]) : "-") </td>
                                            <td>
                                                @(
                                                    ViewBag.Farm2?.Tables[0]?.Rows[i]["net_return"] ?? ""
                                                    )
                                            </td>
                                            <td>
                                                @(
                                                    ViewBag.Farm2?.Tables[0]?.Rows[i]["production_cost"] ?? ""
                                                    )
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="8"> data not available.</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>