InternationalWaterWebApp/InternationalWaterWebApp/Controllers/AdvisorController.cs
using InternationalWaterWebApp.Library.Common;
using InternationalWaterWebApp.Library.ViewModel;
using InternationalWaterWebApp.Models;
using InternationalWaterWebApp.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace InternationalWaterWebApp.Controllers
{
    [AuthorizationCS((int)UserTypeEnum.Agronomist)]
    public class AdvisorController : BaseController
    {
        private CommonMethods commonMethods;
        private CommonController _CommonController;
        private EncryptDecryptData encryptDecryptData;

        public AdvisorController()
        {
            commonMethods = new CommonMethods();
            _CommonController = new CommonController();
            encryptDecryptData = new EncryptDecryptData();
        }

        public IActionResult Landing(string? id,int? field)
        {
            ViewBag.fieldtab = field;
            
            IMasterRepository _masterRepository = new MasterRepository();
            object[] userParams = { "_ActionType", "_Advisor_Id"};
            object[] userFieldValues = { "GetAllFieldsForAdvisor" , LoginUserId };
            object[] userPrdoucerValues = { "GetAllProducersForAdvisor" , LoginUserId };
            DataSet DsFieldData = null;
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.fieldtab = 1;
                string producerId = encryptDecryptData.Decryptdata(id);

                object[] userParams1 = { "_ActionType", "_producer_id" };
                object[] userValues = { "GetFieldByProducerId", producerId };
                string query = $"SELECT * from  \"FSRCalc\".water_producer_ref (datarefcursor => 'data',{userParams1[0]} => '{userValues[0]}',{userParams1[1]} => {userValues[1]});";
                DsFieldData = _masterRepository.GetAndSelectTableItems(query);
                ViewBag.Field = DsFieldData;
            }
            else
            {
                string QueryField = $"SELECT * from \"FSRCalc\".water_advisorfield_ref (datarefcursor => 'data',{userParams[0]} => '{userFieldValues[0]}', {userParams[1]} => '{userFieldValues[1]}');";
                DsFieldData = _masterRepository.GetAndSelectTableItems(QueryField);
                ViewBag.Field = DsFieldData; // fields data

            }
                string QueryProducer = $"SELECT * from \"FSRCalc\".water_advisorfield_ref (datarefcursor => 'data',{userParams[0]} => '{userPrdoucerValues[0]}', {userParams[1]} => '{userPrdoucerValues[1]}');";
                DataSet DsProducerData = _masterRepository.GetAndSelectTableItems(QueryProducer);
                ViewBag.Producer = DsProducerData;
            return View();
        }
    }
}

InternationalWaterWebApp/InternationalWaterWebApp/Controllers/CommonController.cs
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;
using InternationalWaterWebApp.Library.Common;
using InternationalWaterWebApp.Library.DatabaseConnection;
using InternationalWaterWebApp.Library.ViewModel;
using InternationalWaterWebApp.Models;
using InternationalWaterWebApp.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using System.Data;
using System.Drawing.Drawing2D;
using System.Text.RegularExpressions;

namespace InternationalWaterWebApp.Controllers
{
    [AuthorizationCS(new int[] { (int)UserTypeEnum.Admin, (int)UserTypeEnum.Producer, (int)UserTypeEnum.Agronomist })]
    public class CommonController : BaseController
    {
        private CommonMethods commonMethods;
        private EncryptDecryptData encryptDecryptData;
        private static HttpClient _httpClient = new HttpClient();

        public CommonController()
        {
            commonMethods = new CommonMethods();
            encryptDecryptData = new EncryptDecryptData();
        }

        public IActionResult SplashPage()
        {
            return View();
        }

        public IActionResult ChangePassword()
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("Id")))
                {
                    return RedirectToAction("Login");
                }

                ViewBag.UserRole = LoginUserRoleId;

                string RefererUrl = commonMethods.GetRefererUrl(Request);

                if (!string.IsNullOrEmpty(RefererUrl))
                    if (RefererUrl != "/" && RefererUrl.ToLower() != "/login")
                    {
                        ViewBag.ReturnUrl = RefererUrl;
                    }

                return View();
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public IActionResult ChangePassword(User user, string Confirm)
        {
            try
            {
                if (LoginUserId > 0)
                {
                    if (user.Password == Confirm)
                    {
                        user.Id = LoginUserId;
                        bool changed = commonMethods.ChangePassword(user);

                        user.UserRole = LoginUserRoleId;
                        TempData["Success"] = "Password has been changed successfully.";

                        if (user.UserRole == (int)UserTypeEnum.Admin)
                            return Redirect("/Admin/Landing");
                        else if (user.UserRole == (int)UserTypeEnum.Producer)
                            return Redirect("/Producer/Landing");
                        else
                            return RedirectToAction("Error");
                    }
                    else
                    {
                        TempData["Error"] = "Password and Confirm Password should be matched";
                        return View();
                    }
                }
                else
                    return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Error");
            }
        }

        public IActionResult ResetPassword()
        {
            try
            {
                string SiteUrl = RootDirectoryPath.SiteURL;
                string RefererUrl = commonMethods.GetRefererUrl(Request);
                ViewBag.ReturnUrl = SiteUrl + RefererUrl;
                return View();
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public IActionResult ResetPassword(User user)
        {
            try
            {
                IMasterRepository _masterRepository = new MasterRepository();
                if (user != null)
                {

                    // check to user exist or not
                    string SelectQuery = $"SELECT * from  \"Users\".water_getallusers_ref (datarefcursor => 'data',_ActionType => 'GetUserByEmail', _email => '{user.Email}')";
                    DataSet DsData = _masterRepository.GetAndSelectTableItems(SelectQuery);

                    if (DsData.Tables[0].Rows.Count > 0)
                    {
                        string Password = RandomPasswordGenerator.GeneratePassword();
                        object[] userParams = { "_ActionType", "_email", "_password" };
                        object[] userValues = { "ChangePasswordByEmail", user.Email, Password };
                        object[] userSqlDbTypes = { "nvarchar", "int", "nvarchar" };

                        //update password on database
                        //long? data = _masterRepository.InsertUpdate($"SELECT * from water_getallusers_ref (datarefcursor := 'data',{userParams[0]} => '{userValues[0]}',{userParams[1]} => '{userValues[1]}',{userParams[2]} => '{userValues[2]}');");
                        DataSet data = _masterRepository.GetAndSelectTableItems($"SELECT * from  \"Users\".water_getallusers_ref (datarefcursor := 'data',{userParams[0]} => '{userValues[0]}',{userParams[1]} => '{userValues[1]}',{userParams[2]} => '{userValues[2]}');");

                        if (data != null)
                        {
                            // Reset Password mail send for new generated password
                            bool MailProce = SendEmailToResetPassowrd(user.Email, Password, user.FirstName, user.LastName);
                            if (MailProce == true)
                            {
                                TempData["Success"] = "Password has been reset successfully, Plesae check your email";
                                return RedirectToAction("Login", "WebApp");
                            }
                            else
                            {
                                TempData["Error"] = "Password has been reset successfully, Error has occured while sending an email.";
                                return View();
                            }
                        }
                        return RedirectToAction("Login", "WebApp");
                    }
                    else
                    {
                        TempData["Error"] = "User not found with current email, Please check your email.";
                        return View();
                    }
                }
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Error");
            }
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult LoginSelection(string userEmail, string userPass, int? userType, string userTypes)
        {
            try
            {
                User user = new User();
                //ViewBag.userTypes = userTypes;
                user.Email = userEmail;
                user.Password = userPass;
                return View(user);
            }
            catch (Exception ex)
            {
                Log.LogError(ex);
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        [Route("/{controller}/{action}/{Id}")]
        public IActionResult MyFieldEdit(string id)
        {
            string row = encryptDecryptData.Decryptdata(id);
            ViewBag.UserRole = LoginUserRoleId;
            IMasterRepository _masterRepository = new MasterRepository();
            try
            {

                ViewBag.StateOptions = CommonMethods.GetStateOptions(includeCode: true);

                object[] agrParams = { "_ActionType", "_field_id" };
                object[] agrValues = { "GetMyFieldsEditData", row };
                //DataSet FieldData = _masterRepository.GetAndSelectTableItems($"select producer_id, field_id , name, street_address, city , state_name , zip , county , township , range , section , section_quarter , farm_id from fields where field_id = {row}");
                DataSet FieldData = _masterRepository.GetAndSelectTableItems($"SELECT * from  \"FSRCalc\".water_fields_ref (datarefcursor := 'data',{agrParams[0]} => '{agrValues[0]}', {agrParams[1]} => {agrValues[1]});");
                MyFields field = new MyFields
                {
                    Field_Id = (int)FieldData.Tables[0].Rows[0]["field_id"],
                    Field_Name = Convert.ToString(FieldData.Tables[0].Rows[0]["name"]),
                    Street_Address = Convert.ToString(FieldData.Tables[0].Rows[0]["street_address"]),
                    City = Convert.ToString(FieldData.Tables[0].Rows[0]["city"]),
                    State = Convert.ToString(FieldData.Tables[0].Rows[0]["state"]),
                    Zip = FieldData.Tables[0].Rows[0]["zip"] != DBNull.Value ? Convert.ToString(FieldData.Tables[0].Rows[0]["zip"]) : "",
                    County = Convert.ToString(FieldData.Tables[0].Rows[0]["county"]),
                    Township = Convert.ToString(FieldData.Tables[0].Rows[0]["township"]),
                    Range = Convert.ToString(FieldData.Tables[0].Rows[0]["range"]),
                    Section = Convert.ToString(FieldData.Tables[0].Rows[0]["section"]),
                    Section_Quarter = Convert.ToString(FieldData.Tables[0].Rows[0]["section_quarter"]),
                    SectionHalf = Convert.ToString(FieldData.Tables[0].Rows[0]["section_half"]),
                    Farm_Id = (int)FieldData.Tables[0].Rows[0]["farm_id"],
                    ProducerId = (int)FieldData.Tables[0].Rows[0]["producer_id"]
                };

                ViewBag.FieldName = field.Field_Name;

InternationalWaterWebApp/InternationalWaterWebApp/Views/Advisor/Landing.cshtml
@using InternationalWaterWebApp.Library.Common;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    ViewData["Title"] = "Landing Page";
    EncryptDecryptData enc = new EncryptDecryptData();
    string userName = HttpContextAccessor.HttpContext.Session.GetString("FirstName");
}

@if (!string.IsNullOrWhiteSpace(Convert.ToString(TempData["Success"])))
{
    <div class="alert alert-success mt-3" role="alert">
        @TempData["Success"]
    </div>
}

<section class="GreyBG rounded-3 py-3">
    <div class="container-fluid">
        <div class="row g-3">
            <div class="col-12">
                <div class="bg-white br-10 FarmFiled">
                    <div id="TabBar">
                        <ul class="nav nav-pills" id="pills-tab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="pills-Producers-tab" data-bs-toggle="pill"
                                        data-bs-target="#pills-Producers" type="button" role="tab" aria-controls="pills-Producers"
                                        aria-selected="true">
                                    Producers
                                </button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="pills-MyFields-tab" data-bs-toggle="pill"
                                        data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile"
                                        aria-selected="false">
                                    Fields
                                </button>
                            </li>
                        </ul>
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active p-4" id="pills-Producers" role="tabpanel"
                                 aria-labelledby="pills-Producers-tab">
                                 <a id="btn_table_opt" class="bg-green btn ms-3" asp-controller="Common" asp-action="ProducersAddEdit" asp-route-id="0">Add Producer</a>
                                @if (ViewBag.Producer != null && ViewBag.Producer.Tables.Count > 0 && ViewBag.Producer.Tables[0].Rows != null)
                                {
                                    <table class="table table-striped table-responsive table-borderless" id="AdvisorLandingProducer">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Field</th>
                                                @*<th>Zones</th>*@
                                                <th>Email</th>
                                                <th>Phone</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (System.Data.DataRow Row in ViewBag.Producer.Tables[0].Rows)
                                            {
                                                <tr>
                                                    @*<td>@Convert.ToString(Row["first_name"]) @Convert.ToString(Row["last_name"])</td>*@
                                                    <td> <a asp-controller="Advisor" asp-action="Landing" asp-route-id="@enc.Encryptdata(Convert.ToString(Row["producer_id"]))">@Convert.ToString(Row["first_name"]) @Convert.ToString(Row["last_name"])</a></td>
                                                  
                                                    <td>@Convert.ToString(Row["num_fields"])</td>
                                                    @*<td>@Convert.ToString(Row["farm_name"])</td>*@
                                                    @*<td>@Convert.ToString(Row["Zone_count"])</td>*@
                                                    <td>@Convert.ToString(Row["email"])</td>
                                                    <td>@Convert.ToString(Row["phone_number"])</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <div>@CommonMethods.GetEnumDescription(InternationalWaterWebApp.Library.ViewModel.ValidationMessages.NoDataFound)</div>
                                }
                            </div>
                            <div class="tab-pane fade p-4" id="pills-profile" role="tabpanel"
                                 aria-labelledby="pills-MyFields-tab">
                                @if (ViewBag.Field != null && ViewBag.Field.Tables.Count > 0 && ViewBag.Field.Tables[0].Rows.Count > 0)
                                {
                                    <table class="table table-striped table-responsive table-borderless" id="AdvisorLandingFields">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Farm</th>
                                                <th>Zones</th>
                                                <th>Producer</th>
                                                <th>Plans</th>
                                                <th>Address</th>
                                                <th>City</th>
                                                <th>State</th>
                                                <th>Advisor Plans</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (System.Data.DataRow Row in ViewBag.Field.Tables[0].Rows)
                                            {
                                                <tr>
                                                    <td>@Convert.ToString(Row["field_id"])</td>
                                                    <td><a asp-controller="Common" asp-action="MyFieldEdit" asp-route-id="@enc.Encryptdata(Convert.ToString(Row["field_id"]))">@Convert.ToString(Row["Field_Name"])</a></td>
                                                    <td>@Convert.ToString(Row["farm_name"])</td>
                                                    <td>@Convert.ToString(Row["Zone_count"])</td>
                                                    <td>@Convert.ToString(Row["Prod_FName"]) @Convert.ToString(Row["Prod_LName"])</td>
                                                    <td>@Convert.ToString(Row["Plans"])</td>
                                                    <td>@Convert.ToString(Row["street_address"])</td>
                                                    <td>@Convert.ToString(Row["city"])</td>
                                                    <td>@Convert.ToString(Row["state_name"])</td>
                                                    <td><a asp-controller="Common" asp-action="MyFieldsDetails" asp-route-id="@enc.Encryptdata(Convert.ToString(Row["field_id"]))" asp-route-name="@Row["Field_Name"]">View</a></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <div>@CommonMethods.GetEnumDescription(InternationalWaterWebApp.Library.ViewModel.ValidationMessages.NoDataFound)</div>
                                }
                        </div>
                    </div>
                </div>
            </div>
           @* <div class="col-lg-4 col-12">
                <div class="br-10 bg-white p-3 mb-3">
                    <div class="MessAdvisr">
                        <div class="Heading">
                            <h4>My Info</h4>
                        </div>
                        <a href="javascript:;" class="MessAdvisrDetail mb-2">
                            <i class="bi bi-person"></i>
                            <span>@userName</span>
                        </a>
                        <a href="javascript:;" class="MessAdvisrDetail mb-2">
                            <i class="bi bi-at"></i>
                            <span>mymail@gmail.com</span>
                        </a>
                        <a href="javascript:;" class="MessAdvisrDetail mb-4">
                            <i class="bi bi-telephone-fill"></i>
                            <span> (1) 234 567 8900 </span>
                        </a>*@
                       @* <div class="d-grid bg-green advsrBTN">
                            <a href="#" class="btn" role="button" data-bs-toggle="button">Toggle link</a>
                        </div>*@
                    @*</div>
                </div>
        </div>*@
        </div>
    </div>
    </div>
</section>

<script>
    window.onload = function () {
      
        if ('@ViewBag.fieldtab' == 1) { // Check the value of the ViewBag field correctly
            var btn = document.getElementById("pills-MyFields-tab");
            if (btn) {
                btn.click();
            }
        }
    };
</script>